/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ProductOptionCombination = {
  _type: "productOptionCombination";
  selections?: Array<
    {
      _key: string;
    } & ProductOptionSelection
  >;
  sku?: string;
  price?: number;
  stock?: number;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ProductOptionSelection = {
  _type: "productOptionSelection";
  optionKey?: string;
  value?: string;
};

export type ProductOptionGroup = {
  _type: "productOptionGroup";
  key?: string;
  name?: string;
  helpText?: string;
  values?: Array<
    {
      _key: string;
    } & ProductOptionValue
  >;
};

export type ProductOptionValue = {
  _type: "productOptionValue";
  label?: string;
  code?: string;
};

export type Table = {
  _type: "table";
  headers?: Array<string>;
  rows?: Array<
    {
      _key: string;
    } & TableRow
  >;
};

export type TableRow = {
  _type: "tableRow";
  cells?: Array<string>;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Table)
  >;
  author?: AuthorReference;
  brandRef?: BrandReference;
  tags?: Array<string>;
  publishedAt?: string;
  featured?: boolean;
  seoTitle?: string;
  seoDescription?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  role?: string;
  bio?: string;
};

export type Translation = {
  _id: string;
  _type: "translation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key?: string;
  locale?: "en" | "fr" | "de" | "es" | "it" | "fi" | "sv";
  structured?: boolean;
  value?: string;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  receiptUrl?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products?: Array<{
    product?: ProductReference;
    quantity?: number;
    selectedVariant?: {
      color?: string;
      size?: string;
      variantSku?: string;
      price?: number;
      options?: Array<{
        optionKey?: string;
        value?: string;
        _type: "optionSelection";
        _key: string;
      }>;
    };
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  paymentMethod?: "stripe" | "paypal";
  status?: "pending" | "paid" | "shipped" | "delivered" | "cancelled";
  orderDate?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
    _key: string;
  }>;
  intro?: string;
  seoTitle?: string;
  seoDescription?: string;
  description?: string;
  brand?: string;
  brandRef?: BrandReference;
  sku?: string;
  gender?: string;
  nickname?: string;
  releaseDate?: string;
  variants?: Array<{
    color?: string;
    size?: string;
    variantSku?: string;
    stock?: number;
    price?: number;
    variantImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "variant";
    _key: string;
  }>;
  options?: Array<
    {
      _key: string;
    } & ProductOptionGroup
  >;
  optionCombinations?: Array<
    {
      _key: string;
    } & ProductOptionCombination
  >;
  price?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  status?: "new" | "hot" | "sale";
  productType?: "tshirt" | "jacket" | "pants" | "hoodie" | "short" | "others";
  osType?: string;
  operatingSystemsSupported?: string;
  versionType?: string;
  productStatus?: string;
  placeOfOrigin?: string;
  brandName?: string;
  activation?: string;
  shippingMethod?: string;
  packageInclude?: string;
  language?: string;
  warranty?: string;
  deliveryTime?: string;
  support?: string;
  function?: string;
  paymentMethods?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  brandRef?: BrandReference;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  seoTitle?: string;
  seoDescription?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  };
  officialPartner?: boolean;
  showPosts?: boolean;
  relatedCategories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ProductOptionCombination
  | ProductOptionSelection
  | ProductOptionGroup
  | ProductOptionValue
  | Table
  | TableRow
  | AuthorReference
  | BrandReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Author
  | Translation
  | ProductReference
  | Order
  | CategoryReference
  | Product
  | Category
  | Brand
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: app/api/order/route.ts
// Variable: GET_ORDER_BY_NUMBER_QUERY
// Query: *[_type == 'order' && orderNumber == $orderNumber][0]{      ...,products[]{        ...,product->      }    }
export type GET_ORDER_BY_NUMBER_QUERY_RESULT = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  receiptUrl?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        altText?: string;
        _type: "image";
        _key: string;
      }>;
      intro?: string;
      seoTitle?: string;
      seoDescription?: string;
      description?: string;
      brand?: string;
      brandRef?: BrandReference;
      sku?: string;
      gender?: string;
      nickname?: string;
      releaseDate?: string;
      variants?: Array<{
        color?: string;
        size?: string;
        variantSku?: string;
        stock?: number;
        price?: number;
        variantImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        _type: "variant";
        _key: string;
      }>;
      options?: Array<
        {
          _key: string;
        } & ProductOptionGroup
      >;
      optionCombinations?: Array<
        {
          _key: string;
        } & ProductOptionCombination
      >;
      price?: number;
      discount?: number;
      categories?: Array<
        {
          _key: string;
        } & CategoryReference
      >;
      stock?: number;
      status?: "hot" | "new" | "sale";
      productType?:
        "hoodie" | "jacket" | "others" | "pants" | "short" | "tshirt";
      osType?: string;
      operatingSystemsSupported?: string;
      versionType?: string;
      productStatus?: string;
      placeOfOrigin?: string;
      brandName?: string;
      activation?: string;
      shippingMethod?: string;
      packageInclude?: string;
      language?: string;
      warranty?: string;
      deliveryTime?: string;
      support?: string;
      function?: string;
      paymentMethods?: string;
    } | null;
    quantity?: number;
    selectedVariant?: {
      color?: string;
      size?: string;
      variantSku?: string;
      price?: number;
      options?: Array<{
        optionKey?: string;
        value?: string;
        _type: "optionSelection";
        _key: string;
      }>;
    };
    _key: string;
  }> | null;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  paymentMethod?: "paypal" | "stripe";
  status?: "cancelled" | "delivered" | "paid" | "pending" | "shipped";
  orderDate?: string;
} | null;

// Source: sanity/helpers/blogQueries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post"] | order(publishedAt desc) {  _id,  _createdAt,  _updatedAt,  title,  slug,  excerpt,  coverImage,  body,  publishedAt,  featured,  tags,  seoTitle,  seoDescription,  "author": author->{    _id,    name,    role,    bio,    slug,    image  },  "brandRef": brandRef->{    _id,    title,    slug  }}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  _createdAt: string;
  _updatedAt: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  body: Array<
    | ({
        _key: string;
      } & Table)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  publishedAt: string | null;
  featured: boolean | null;
  tags: Array<string> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  author: {
    _id: string;
    name: string | null;
    role: string | null;
    bio: string | null;
    slug: Slug | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  brandRef: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
}>;

// Source: sanity/helpers/blogQueries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {  _id,  _createdAt,  _updatedAt,  title,  slug,  excerpt,  coverImage,  body,  publishedAt,  featured,  tags,  seoTitle,  seoDescription,  "author": author->{    _id,    name,    role,    bio,    slug,    image  },  "brandRef": brandRef->{    _id,    title,    slug  }}
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _createdAt: string;
  _updatedAt: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  body: Array<
    | ({
        _key: string;
      } & Table)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  publishedAt: string | null;
  featured: boolean | null;
  tags: Array<string> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  author: {
    _id: string;
    name: string | null;
    role: string | null;
    bio: string | null;
    slug: Slug | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  brandRef: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
} | null;

// Source: sanity/helpers/blogQueries.ts
// Variable: LATEST_POSTS_QUERY
// Query: *[_type == "post" && (!defined($excludeSlug) || slug.current != $excludeSlug)] | order(publishedAt desc)[0...$limit] {      _id,      title,      slug,      excerpt,      coverImage,      publishedAt,      featured,      tags,      "author": author->{        _id,        name,        role,        slug,        image      }    }
export type LATEST_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  publishedAt: string | null;
  featured: boolean | null;
  tags: Array<string> | null;
  author: {
    _id: string;
    name: string | null;
    role: string | null;
    slug: Slug | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: sanity/helpers/brandQueries.ts
// Variable: BRAND_BY_SLUG_QUERY
// Query: *[_type == "brand" && slug.current == $slug][0] {  _id,  title,  slug,  description,  seoTitle,  seoDescription,  logo,  officialPartner,  showPosts,  "categories": relatedCategories[]->{    _id,    title,    slug,    description,    "productCount": count(*[_type == "product" && references(^._id)])  },  "products": *[_type == "product" && references(^._id)]{    _id,    name,    slug,    intro,    price,    discount,    images,    stock  } | order(name asc),  "posts": *[_type == "post" && references(^._id)] | order(publishedAt desc){    _id,    title,    slug,    excerpt,    coverImage,    body,    _createdAt,    publishedAt,    tags,    featured,    "author": author->{ _id, name }  }}
export type BRAND_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
  } | null;
  officialPartner: boolean | null;
  showPosts: boolean | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    description: string | null;
    productCount: number;
  }> | null;
  products: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    intro: string | null;
    price: number | null;
    discount: number | null;
    images: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      altText?: string;
      _type: "image";
      _key: string;
    }> | null;
    stock: number | null;
  }>;
  posts: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    excerpt: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    body: Array<
      | ({
          _key: string;
        } & Table)
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?:
            "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }
    > | null;
    _createdAt: string;
    publishedAt: string | null;
    tags: Array<string> | null;
    featured: boolean | null;
    author: {
      _id: string;
      name: string | null;
    } | null;
  }>;
} | null;

// Source: sanity/helpers/brandQueries.ts
// Variable: BRANDS_QUERY
// Query: *[_type == "brand"]{ _id, title, slug, description, seoTitle, seoDescription, officialPartner } | order(title asc)
export type BRANDS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  officialPartner: boolean | null;
}>;

// Source: sanity/helpers/brandQueries.ts
// Variable: ELIGIBLE_BRANDS_QUERY
// Query: *[_type == "brand" && count(*[_type == "product" && references(^._id)]) > 0]{ _id, title, slug, description, seoTitle, seoDescription, officialPartner } | order(title asc)
export type ELIGIBLE_BRANDS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  officialPartner: boolean | null;
}>;

// Source: sanity/helpers/brandQueries.ts
// Variable: BRAND_SITEMAP_QUERY
// Query: *[_type == "brand" && count(*[_type == "product" && references(^._id)]) > 0]{ _id, "slug": slug.current, _updatedAt } | order(_updatedAt desc)
export type BRAND_SITEMAP_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  _updatedAt: string;
}>;

// Source: sanity/helpers/queries.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == 'product' && slug.current == $slug] | order(name asc) [0]{      ...,      "brandRef": brandRef->{        _id,        title,        slug,        description,        officialPartner      }    }
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    _type: "image";
    _key: string;
  }>;
  intro?: string;
  seoTitle?: string;
  seoDescription?: string;
  description?: string;
  brand?: string;
  brandRef: {
    _id: string;
    title: string | null;
    slug: Slug | null;
    description: string | null;
    officialPartner: boolean | null;
  } | null;
  sku?: string;
  gender?: string;
  nickname?: string;
  releaseDate?: string;
  variants?: Array<{
    color?: string;
    size?: string;
    variantSku?: string;
    stock?: number;
    price?: number;
    variantImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "variant";
    _key: string;
  }>;
  options?: Array<
    {
      _key: string;
    } & ProductOptionGroup
  >;
  optionCombinations?: Array<
    {
      _key: string;
    } & ProductOptionCombination
  >;
  price?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  status?: "hot" | "new" | "sale";
  productType?: "hoodie" | "jacket" | "others" | "pants" | "short" | "tshirt";
  osType?: string;
  operatingSystemsSupported?: string;
  versionType?: string;
  productStatus?: string;
  placeOfOrigin?: string;
  brandName?: string;
  activation?: string;
  shippingMethod?: string;
  packageInclude?: string;
  language?: string;
  warranty?: string;
  deliveryTime?: string;
  support?: string;
  function?: string;
  paymentMethods?: string;
} | null;

// Source: sanity/helpers/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type=="category"] | order(title asc)
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  brandRef?: BrandReference;
}>;

// Source: sanity/helpers/queries.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type=="category" && slug.current == $slug][0]{      _id,      title,      slug,      description,      image,      "brandRef": brandRef->{ _id, title, slug }    }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  brandRef: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
} | null;

// Source: sanity/helpers/queries.ts
// Variable: PRODUCTS_QUERY
// Query: *[_type=="product"]{slug,_updatedAt} | order(_updatedAt desc)
export type PRODUCTS_QUERY_RESULT = Array<{
  slug: Slug | null;
  _updatedAt: string;
}>;

// Source: sanity/helpers/queries.ts
// Variable: MY_ORDERS_QUERY
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderDate desc){    ...,    paymentMethod,    receiptUrl,    products[]{      ...,product->    }  }
export type MY_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  receiptUrl: string | null;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        altText?: string;
        _type: "image";
        _key: string;
      }>;
      intro?: string;
      seoTitle?: string;
      seoDescription?: string;
      description?: string;
      brand?: string;
      brandRef?: BrandReference;
      sku?: string;
      gender?: string;
      nickname?: string;
      releaseDate?: string;
      variants?: Array<{
        color?: string;
        size?: string;
        variantSku?: string;
        stock?: number;
        price?: number;
        variantImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        _type: "variant";
        _key: string;
      }>;
      options?: Array<
        {
          _key: string;
        } & ProductOptionGroup
      >;
      optionCombinations?: Array<
        {
          _key: string;
        } & ProductOptionCombination
      >;
      price?: number;
      discount?: number;
      categories?: Array<
        {
          _key: string;
        } & CategoryReference
      >;
      stock?: number;
      status?: "hot" | "new" | "sale";
      productType?:
        "hoodie" | "jacket" | "others" | "pants" | "short" | "tshirt";
      osType?: string;
      operatingSystemsSupported?: string;
      versionType?: string;
      productStatus?: string;
      placeOfOrigin?: string;
      brandName?: string;
      activation?: string;
      shippingMethod?: string;
      packageInclude?: string;
      language?: string;
      warranty?: string;
      deliveryTime?: string;
      support?: string;
      function?: string;
      paymentMethods?: string;
    } | null;
    quantity?: number;
    selectedVariant?: {
      color?: string;
      size?: string;
      variantSku?: string;
      price?: number;
      options?: Array<{
        optionKey?: string;
        value?: string;
        _type: "optionSelection";
        _key: string;
      }>;
    };
    _key: string;
  }> | null;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  paymentMethod: "paypal" | "stripe" | null;
  status?: "cancelled" | "delivered" | "paid" | "pending" | "shipped";
  orderDate?: string;
}>;

// Source: sanity/helpers/queries.ts
// Variable: ORDER_BY_NUMBER_QUERY
// Query: *[_type == 'order' && orderNumber == $orderNumber][0]{    ...,products[]{      ...,product->    }  }
export type ORDER_BY_NUMBER_QUERY_RESULT = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  receiptUrl?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        altText?: string;
        _type: "image";
        _key: string;
      }>;
      intro?: string;
      seoTitle?: string;
      seoDescription?: string;
      description?: string;
      brand?: string;
      brandRef?: BrandReference;
      sku?: string;
      gender?: string;
      nickname?: string;
      releaseDate?: string;
      variants?: Array<{
        color?: string;
        size?: string;
        variantSku?: string;
        stock?: number;
        price?: number;
        variantImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        _type: "variant";
        _key: string;
      }>;
      options?: Array<
        {
          _key: string;
        } & ProductOptionGroup
      >;
      optionCombinations?: Array<
        {
          _key: string;
        } & ProductOptionCombination
      >;
      price?: number;
      discount?: number;
      categories?: Array<
        {
          _key: string;
        } & CategoryReference
      >;
      stock?: number;
      status?: "hot" | "new" | "sale";
      productType?:
        "hoodie" | "jacket" | "others" | "pants" | "short" | "tshirt";
      osType?: string;
      operatingSystemsSupported?: string;
      versionType?: string;
      productStatus?: string;
      placeOfOrigin?: string;
      brandName?: string;
      activation?: string;
      shippingMethod?: string;
      packageInclude?: string;
      language?: string;
      warranty?: string;
      deliveryTime?: string;
      support?: string;
      function?: string;
      paymentMethods?: string;
    } | null;
    quantity?: number;
    selectedVariant?: {
      color?: string;
      size?: string;
      variantSku?: string;
      price?: number;
      options?: Array<{
        optionKey?: string;
        value?: string;
        _type: "optionSelection";
        _key: string;
      }>;
    };
    _key: string;
  }> | null;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  paymentMethod?: "paypal" | "stripe";
  status?: "cancelled" | "delivered" | "paid" | "pending" | "shipped";
  orderDate?: string;
} | null;

// Source: sanity/helpers/translations.ts
// Variable: TRANSLATIONS_QUERY
// Query: *[_type == 'translation' && locale == $locale]{ key, structured, value }
export type TRANSLATIONS_QUERY_RESULT = Array<{
  key: string | null;
  structured: boolean | null;
  value: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == 'order' && orderNumber == $orderNumber][0]{\n      ...,products[]{\n        ...,product->\n      }\n    }": GET_ORDER_BY_NUMBER_QUERY_RESULT;
    '*[_type == "post"] | order(publishedAt desc) {\n  _id,\n  _createdAt,\n  _updatedAt,\n  title,\n  slug,\n  excerpt,\n  coverImage,\n  body,\n  publishedAt,\n  featured,\n  tags,\n  seoTitle,\n  seoDescription,\n  "author": author->{\n    _id,\n    name,\n    role,\n    bio,\n    slug,\n    image\n  },\n  "brandRef": brandRef->{\n    _id,\n    title,\n    slug\n  }\n}': POSTS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0] {\n  _id,\n  _createdAt,\n  _updatedAt,\n  title,\n  slug,\n  excerpt,\n  coverImage,\n  body,\n  publishedAt,\n  featured,\n  tags,\n  seoTitle,\n  seoDescription,\n  "author": author->{\n    _id,\n    name,\n    role,\n    bio,\n    slug,\n    image\n  },\n  "brandRef": brandRef->{\n    _id,\n    title,\n    slug\n  }\n}': POST_BY_SLUG_QUERY_RESULT;
    '*[_type == "post" && (!defined($excludeSlug) || slug.current != $excludeSlug)] | order(publishedAt desc)[0...$limit] {\n      _id,\n      title,\n      slug,\n      excerpt,\n      coverImage,\n      publishedAt,\n      featured,\n      tags,\n      "author": author->{\n        _id,\n        name,\n        role,\n        slug,\n        image\n      }\n    }': LATEST_POSTS_QUERY_RESULT;
    '*[_type == "brand" && slug.current == $slug][0] {\n  _id,\n  title,\n  slug,\n  description,\n  seoTitle,\n  seoDescription,\n  logo,\n  officialPartner,\n  showPosts,\n  "categories": relatedCategories[]->{\n    _id,\n    title,\n    slug,\n    description,\n    "productCount": count(*[_type == "product" && references(^._id)])\n  },\n  "products": *[_type == "product" && references(^._id)]{\n    _id,\n    name,\n    slug,\n    intro,\n    price,\n    discount,\n    images,\n    stock\n  } | order(name asc),\n  "posts": *[_type == "post" && references(^._id)] | order(publishedAt desc){\n    _id,\n    title,\n    slug,\n    excerpt,\n    coverImage,\n    body,\n    _createdAt,\n    publishedAt,\n    tags,\n    featured,\n    "author": author->{ _id, name }\n  }\n}': BRAND_BY_SLUG_QUERY_RESULT;
    '*[_type == "brand"]{ _id, title, slug, description, seoTitle, seoDescription, officialPartner } | order(title asc)': BRANDS_QUERY_RESULT;
    '*[_type == "brand" && count(*[_type == "product" && references(^._id)]) > 0]{ _id, title, slug, description, seoTitle, seoDescription, officialPartner } | order(title asc)': ELIGIBLE_BRANDS_QUERY_RESULT;
    '*[_type == "brand" && count(*[_type == "product" && references(^._id)]) > 0]{ _id, "slug": slug.current, _updatedAt } | order(_updatedAt desc)': BRAND_SITEMAP_QUERY_RESULT;
    "*[_type == 'product' && slug.current == $slug] | order(name asc) [0]{\n      ...,\n      \"brandRef\": brandRef->{\n        _id,\n        title,\n        slug,\n        description,\n        officialPartner\n      }\n    }": PRODUCT_BY_SLUG_QUERY_RESULT;
    '*[_type=="category"] | order(title asc)': CATEGORIES_QUERY_RESULT;
    '*[_type=="category" && slug.current == $slug][0]{\n      _id,\n      title,\n      slug,\n      description,\n      image,\n      "brandRef": brandRef->{ _id, title, slug }\n    }': CATEGORY_BY_SLUG_QUERY_RESULT;
    '*[_type=="product"]{slug,_updatedAt} | order(_updatedAt desc)': PRODUCTS_QUERY_RESULT;
    "*[_type == 'order' && clerkUserId == $userId] | order(orderDate desc){\n    ...,\n    paymentMethod,\n    receiptUrl,\n    products[]{\n      ...,product->\n    }\n  }": MY_ORDERS_QUERY_RESULT;
    "*[_type == 'order' && orderNumber == $orderNumber][0]{\n    ...,products[]{\n      ...,product->\n    }\n  }": ORDER_BY_NUMBER_QUERY_RESULT;
    "*[_type == 'translation' && locale == $locale]{ key, structured, value }": TRANSLATIONS_QUERY_RESULT;
  }
}
